version: '3'

services:
    deb:
      image: 'bitnami/mongodb:latest'
      ports:
          - 27017:27017
      restart: on-failure
      environment:
          - MONGODB_REPLICA_SET_MODE=primary
          - MONGODB_ADVERTASED_HOSTNAME=localhost
          - ALLOW_EMPTY_PASSWORD=yes